services:
  - type: web
    name: security-status-miniapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webapp/app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false
      - key: DATABASE_PATH
        value: /tmp/security_reports.db
    healthCheckPath: /health
